### PR TITLE
Fix build on current ubuntu

### PR DESCRIPTION
**Pull request by jcupitt**
A couple of small changes are needed to build on Ubuntu 21.04.

### CODE REVIEW

**Comment by danielbeaudreau** [comment]
Thanks. This is currently failing the lint check:
docker.io/library/python:2.7
././src/dcmTags.cpp:28:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]

**Comment by jcupitt** [comment]
Oh, curious, that's not a line I touched. I've removed the space anyway. Thanks for reviewing.

**Comment by danielbeaudreau** [comment]
Unfortunately this does not seem to build on presubmits:

/workspace/src/dcmTags.cpp: In function 'Json::Value readJsonTag(Json::Value, std::string)':
/workspace/src/dcmTags.cpp:33:22: error: could not convert '(& obj.Json::Value::operator[](tag))->Json::Value::operator[](((const char*)(& VALUE)))' from 'Json::Value' to 'bool'
   33 |   if (obj[tag][VALUE]) {
      |                      ^
      |                      |
      |                      Json::Value
[ 96%] Building CXX object CMakeFiles/wsi2dcm.dir/src/wsiToDcm.cpp.o

**Comment by danielbeaudreau** [comment]
Closing as obsolete. Feel free to re-open if anything changes.
